// <auto-generated />
using System;
using BE_Glowpurea.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BE_Glowpurea.Migrations
{
    [DbContext(typeof(DbGlowpureaContext))]
    partial class DbGlowpureaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BE_Glowpurea.Models.Account", b =>
                {
                    b.Property<int>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccountId"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Image")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Provider")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasDefaultValue("Active");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("AccountId")
                        .HasName("PK__Accounts__349DA58630EE5F8B");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "PhoneNumber" }, "UQ_Accounts_PhoneNumber_Filtered")
                        .IsUnique()
                        .HasFilter("([PhoneNumber] IS NOT NULL)");

                    b.HasIndex(new[] { "Email" }, "UQ__Accounts__A9D1053453F81625")
                        .IsUnique();

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.BlogCategory", b =>
                {
                    b.Property<int>("BlogCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BlogCategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogCategoryId"));

                    b.Property<string>("BlogCategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("BlogCategoryId")
                        .HasName("PK__BlogCate__6BD2DA61ABD754AC");

                    b.HasIndex(new[] { "BlogCategoryName" }, "UQ__BlogCate__06725EA7AA656064")
                        .IsUnique();

                    b.ToTable("BlogCategories");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.BlogPost", b =>
                {
                    b.Property<int>("BlogPostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BlogPostID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogPostId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    b.Property<string>("BlogContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlogThumbnail")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BlogTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BlogUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("BlogPostId")
                        .HasName("PK__BlogPost__32174149F15CD456");

                    b.HasIndex("AccountId");

                    b.ToTable("BlogPosts");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CartID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("CartId")
                        .HasName("PK__Cart__51BCD797DEBEE0AF");

                    b.HasIndex("AccountId");

                    b.ToTable("Cart", (string)null);
                });

            modelBuilder.Entity("BE_Glowpurea.Models.CartItem", b =>
                {
                    b.Property<int>("CartItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CartItemID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartItemId"));

                    b.Property<DateTime>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("CartId")
                        .HasColumnType("int")
                        .HasColumnName("CartID");

                    b.Property<decimal>("PriceAtThatTime")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValue("Active");

                    b.HasKey("CartItemId")
                        .HasName("PK__CartItem__488B0B2AC8976898");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("CategoryId")
                        .HasName("PK__Categori__19093A2BBF136F78");

                    b.HasIndex(new[] { "CategoryName" }, "UQ_Categories_CategoryName")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OrderDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("PaidByExternalAmount")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<decimal>("PaidByWalletAmount")
                        .HasColumnType("decimal(14, 2)");

                    b.Property<DateTime?>("PaymentCompletedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("RefundStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValue("None");

                    b.Property<string>("ShippingAddressLine")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ShippingCity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShippingMethod")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShippingName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShippingPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShippingWard")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("OrderId")
                        .HasName("PK__Orders__C3905BAFB423BD5E");

                    b.HasIndex("AccountId");

                    b.HasIndex("StatusId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderDetailID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<bool>("Reviewed")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Total")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("numeric(36, 9)")
                        .HasComputedColumnSql("(([Quantity]*[UnitPrice])*((1)-[Discount]/(100.0)))", true);

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(12, 2)");

                    b.HasKey("OrderDetailId")
                        .HasName("PK__OrderDet__D3B9D30C2ECE41CB");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.OrderStatusHistory", b =>
                {
                    b.Property<int>("OrderStatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("OrderStatusHistoryID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderStatusHistoryId"));

                    b.Property<DateTime>("ChangedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("ChangedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int")
                        .HasColumnName("OrderID");

                    b.Property<int?>("StatusId")
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("OrderStatusHistoryId")
                        .HasName("PK__OrderSta__D16EDBA313180CB8");

                    b.HasIndex("ChangedBy");

                    b.HasIndex("OrderId");

                    b.HasIndex("StatusId");

                    b.ToTable("OrderStatusHistory", (string)null);
                });

            modelBuilder.Entity("BE_Glowpurea.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("CategoryID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProductStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasDefaultValue("Available");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("ShapesId")
                        .HasColumnType("int")
                        .HasColumnName("ShapesID");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("SKU");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("ProductId")
                        .HasName("PK__Products__B40CC6EDCFB9A720");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ShapesId");

                    b.HasIndex(new[] { "Sku" }, "UQ__Products__CA1ECF0DB43A9995")
                        .IsUnique();

                    b.ToTable("Products");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.ProductImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ImageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsMain")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.HasKey("ImageId")
                        .HasName("PK__ProductI__7516F4ECC602F4C4");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.ReviewBlog", b =>
                {
                    b.Property<int>("ReviewBlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReviewBlogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewBlogId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    b.Property<int>("BlogPostId")
                        .HasColumnType("int")
                        .HasColumnName("BlogPostID");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("ReviewBlogId")
                        .HasName("PK__ReviewBl__A19536C0D010D49E");

                    b.HasIndex("BlogPostId");

                    b.HasIndex(new[] { "AccountId", "BlogPostId" }, "UQ_ReviewBlogs_PostAccount")
                        .IsUnique();

                    b.ToTable("ReviewBlogs");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.ReviewBlogReaction", b =>
                {
                    b.Property<int>("ReactionBlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReactionBlogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReactionBlogId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ReactionType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ReviewBlogId")
                        .HasColumnType("int")
                        .HasColumnName("ReviewBlogID");

                    b.HasKey("ReactionBlogId")
                        .HasName("PK__ReviewBl__6A8A0D274E47C44A");

                    b.HasIndex("AccountId");

                    b.HasIndex(new[] { "ReviewBlogId", "AccountId" }, "UQ_ReviewBlogReactions")
                        .IsUnique();

                    b.ToTable("ReviewBlogReactions");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.ReviewBlogReply", b =>
                {
                    b.Property<int>("ReplyBlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReplyBlogID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReplyBlogId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ReviewBlogId")
                        .HasColumnType("int")
                        .HasColumnName("ReviewBlogID");

                    b.HasKey("ReplyBlogId")
                        .HasName("PK__ReviewBl__59963641E67E414D");

                    b.HasIndex("AccountId");

                    b.HasIndex("ReviewBlogId");

                    b.ToTable("ReviewBlogReplies");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.ReviewProduct", b =>
                {
                    b.Property<int>("ReviewProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReviewProductID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewProductId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerifiedPurchase")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("ReviewProductId")
                        .HasName("PK__ReviewPr__02A6803AE50728A2");

                    b.HasIndex("ProductId");

                    b.HasIndex(new[] { "AccountId", "ProductId" }, "UQ_Reviews_ProductAccount")
                        .IsUnique();

                    b.ToTable("ReviewProducts");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.ReviewProductImage", b =>
                {
                    b.Property<int>("ReviewProductImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReviewProductImageID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewProductImageId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ReviewProductId")
                        .HasColumnType("int")
                        .HasColumnName("ReviewProductID");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("ReviewProductImageId")
                        .HasName("PK__ReviewPr__013E0F1E8841590F");

                    b.HasIndex("ReviewProductId");

                    b.ToTable("ReviewProductImages");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.ReviewProductReaction", b =>
                {
                    b.Property<int>("ReactionProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReactionProductID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReactionProductId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ReactionType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("ReviewProductId")
                        .HasColumnType("int")
                        .HasColumnName("ReviewProductID");

                    b.HasKey("ReactionProductId")
                        .HasName("PK__ReviewPr__B56FCAF126CE18CC");

                    b.HasIndex("AccountId");

                    b.HasIndex(new[] { "ReviewProductId", "AccountId" }, "UQ_ReviewProductReactions")
                        .IsUnique();

                    b.ToTable("ReviewProductReactions");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.ReviewProductReply", b =>
                {
                    b.Property<int>("ReplyProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReplyProductID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReplyProductId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ReviewProductId")
                        .HasColumnType("int")
                        .HasColumnName("ReviewProductID");

                    b.HasKey("ReplyProductId")
                        .HasName("PK__ReviewPr__2DCE233C5317F637");

                    b.HasIndex("AccountId");

                    b.HasIndex("ReviewProductId");

                    b.ToTable("ReviewProductReplies");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RoleID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE3A64DE7FCA");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Roles__8A2B6160A622BCCC")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.Shape", b =>
                {
                    b.Property<int>("ShapesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ShapesID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShapesId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ShapesName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ShapesId")
                        .HasName("PK__Shapes__590E7E2AB57D7E34");

                    b.ToTable("Shapes");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.StatusOrder", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StatusID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.HasKey("StatusId")
                        .HasName("PK__StatusOr__C8EE2043C37D7245");

                    b.ToTable("StatusOrders");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.Wishlist", b =>
                {
                    b.Property<int>("WishlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("WishlistID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WishlistId"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int")
                        .HasColumnName("AccountID");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("ProductID");

                    b.HasKey("WishlistId")
                        .HasName("PK__Wishlist__233189CBCB4337F5");

                    b.HasIndex("ProductId");

                    b.HasIndex(new[] { "AccountId", "ProductId" }, "UQ_Wishlists")
                        .IsUnique();

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("BlogPostCategory", b =>
                {
                    b.Property<int>("BlogPostId")
                        .HasColumnType("int")
                        .HasColumnName("BlogPostID");

                    b.Property<int>("BlogCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("BlogCategoryID");

                    b.HasKey("BlogPostId", "BlogCategoryId")
                        .HasName("PK__BlogPost__34AA6CEFB1A7A93E");

                    b.HasIndex("BlogCategoryId");

                    b.ToTable("BlogPostCategories", (string)null);
                });

            modelBuilder.Entity("BE_Glowpurea.Models.Account", b =>
                {
                    b.HasOne("BE_Glowpurea.Models.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Accounts_Roles");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.BlogPost", b =>
                {
                    b.HasOne("BE_Glowpurea.Models.Account", "Account")
                        .WithMany("BlogPosts")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK_BlogPosts_Accounts");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.Cart", b =>
                {
                    b.HasOne("BE_Glowpurea.Models.Account", "Account")
                        .WithMany("Carts")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Cart_Accounts");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.CartItem", b =>
                {
                    b.HasOne("BE_Glowpurea.Models.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CartItems_Cart");

                    b.HasOne("BE_Glowpurea.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_CartItems_Products");

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.Order", b =>
                {
                    b.HasOne("BE_Glowpurea.Models.Account", "Account")
                        .WithMany("Orders")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_Accounts");

                    b.HasOne("BE_Glowpurea.Models.StatusOrder", "Status")
                        .WithMany("Orders")
                        .HasForeignKey("StatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Orders_StatusOrder");

                    b.Navigation("Account");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.OrderDetail", b =>
                {
                    b.HasOne("BE_Glowpurea.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OrderDetails_Orders");

                    b.HasOne("BE_Glowpurea.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_OrderDetails_Products");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.OrderStatusHistory", b =>
                {
                    b.HasOne("BE_Glowpurea.Models.Account", "ChangedByNavigation")
                        .WithMany("OrderStatusHistories")
                        .HasForeignKey("ChangedBy")
                        .HasConstraintName("FK_OSH_ChangedBy");

                    b.HasOne("BE_Glowpurea.Models.Order", "Order")
                        .WithMany("OrderStatusHistories")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_OSH_Orders");

                    b.HasOne("BE_Glowpurea.Models.StatusOrder", "Status")
                        .WithMany("OrderStatusHistories")
                        .HasForeignKey("StatusId")
                        .HasConstraintName("FK_OSH_StatusOrder");

                    b.Navigation("ChangedByNavigation");

                    b.Navigation("Order");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.Product", b =>
                {
                    b.HasOne("BE_Glowpurea.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Products_Categories");

                    b.HasOne("BE_Glowpurea.Models.Shape", "Shapes")
                        .WithMany("Products")
                        .HasForeignKey("ShapesId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Products_Shapes");

                    b.Navigation("Category");

                    b.Navigation("Shapes");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.ProductImage", b =>
                {
                    b.HasOne("BE_Glowpurea.Models.Product", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProductImages_Products");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.ReviewBlog", b =>
                {
                    b.HasOne("BE_Glowpurea.Models.Account", "Account")
                        .WithMany("ReviewBlogs")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ReviewBlogs_Accounts");

                    b.HasOne("BE_Glowpurea.Models.BlogPost", "BlogPost")
                        .WithMany("ReviewBlogs")
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ReviewBlogs_Posts");

                    b.Navigation("Account");

                    b.Navigation("BlogPost");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.ReviewBlogReaction", b =>
                {
                    b.HasOne("BE_Glowpurea.Models.Account", "Account")
                        .WithMany("ReviewBlogReactions")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK_ReviewBlogReactions_Accounts");

                    b.HasOne("BE_Glowpurea.Models.ReviewBlog", "ReviewBlog")
                        .WithMany("ReviewBlogReactions")
                        .HasForeignKey("ReviewBlogId")
                        .IsRequired()
                        .HasConstraintName("FK_ReviewBlogReactions_ReviewBlogs");

                    b.Navigation("Account");

                    b.Navigation("ReviewBlog");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.ReviewBlogReply", b =>
                {
                    b.HasOne("BE_Glowpurea.Models.Account", "Account")
                        .WithMany("ReviewBlogReplies")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK_ReviewBlogReplies_Accounts");

                    b.HasOne("BE_Glowpurea.Models.ReviewBlog", "ReviewBlog")
                        .WithMany("ReviewBlogReplies")
                        .HasForeignKey("ReviewBlogId")
                        .IsRequired()
                        .HasConstraintName("FK_ReviewBlogReplies_ReviewBlogs");

                    b.Navigation("Account");

                    b.Navigation("ReviewBlog");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.ReviewProduct", b =>
                {
                    b.HasOne("BE_Glowpurea.Models.Account", "Account")
                        .WithMany("ReviewProducts")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Reviews_Accounts");

                    b.HasOne("BE_Glowpurea.Models.Product", "Product")
                        .WithMany("ReviewProducts")
                        .HasForeignKey("ProductId")
                        .IsRequired()
                        .HasConstraintName("FK_Reviews_Products");

                    b.Navigation("Account");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.ReviewProductImage", b =>
                {
                    b.HasOne("BE_Glowpurea.Models.ReviewProduct", "ReviewProduct")
                        .WithMany("ReviewProductImages")
                        .HasForeignKey("ReviewProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ReviewProdImages_ReviewProducts");

                    b.Navigation("ReviewProduct");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.ReviewProductReaction", b =>
                {
                    b.HasOne("BE_Glowpurea.Models.Account", "Account")
                        .WithMany("ReviewProductReactions")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK_ReviewProdReactions_Accounts");

                    b.HasOne("BE_Glowpurea.Models.ReviewProduct", "ReviewProduct")
                        .WithMany("ReviewProductReactions")
                        .HasForeignKey("ReviewProductId")
                        .IsRequired()
                        .HasConstraintName("FK_ReviewProdReactions_Reviews");

                    b.Navigation("Account");

                    b.Navigation("ReviewProduct");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.ReviewProductReply", b =>
                {
                    b.HasOne("BE_Glowpurea.Models.Account", "Account")
                        .WithMany("ReviewProductReplies")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK_ReviewProdReplies_Accounts");

                    b.HasOne("BE_Glowpurea.Models.ReviewProduct", "ReviewProduct")
                        .WithMany("ReviewProductReplies")
                        .HasForeignKey("ReviewProductId")
                        .IsRequired()
                        .HasConstraintName("FK_ReviewProdReplies_Reviews");

                    b.Navigation("Account");

                    b.Navigation("ReviewProduct");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.Wishlist", b =>
                {
                    b.HasOne("BE_Glowpurea.Models.Account", "Account")
                        .WithMany("Wishlists")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Wishlists_Accounts");

                    b.HasOne("BE_Glowpurea.Models.Product", "Product")
                        .WithMany("Wishlists")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Wishlists_Products");

                    b.Navigation("Account");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BlogPostCategory", b =>
                {
                    b.HasOne("BE_Glowpurea.Models.BlogCategory", null)
                        .WithMany()
                        .HasForeignKey("BlogCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BlogPostCategories_Categories");

                    b.HasOne("BE_Glowpurea.Models.BlogPost", null)
                        .WithMany()
                        .HasForeignKey("BlogPostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_BlogPostCategories_Posts");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.Account", b =>
                {
                    b.Navigation("BlogPosts");

                    b.Navigation("Carts");

                    b.Navigation("OrderStatusHistories");

                    b.Navigation("Orders");

                    b.Navigation("ReviewBlogReactions");

                    b.Navigation("ReviewBlogReplies");

                    b.Navigation("ReviewBlogs");

                    b.Navigation("ReviewProductReactions");

                    b.Navigation("ReviewProductReplies");

                    b.Navigation("ReviewProducts");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.BlogPost", b =>
                {
                    b.Navigation("ReviewBlogs");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("OrderStatusHistories");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("OrderDetails");

                    b.Navigation("ProductImages");

                    b.Navigation("ReviewProducts");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.ReviewBlog", b =>
                {
                    b.Navigation("ReviewBlogReactions");

                    b.Navigation("ReviewBlogReplies");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.ReviewProduct", b =>
                {
                    b.Navigation("ReviewProductImages");

                    b.Navigation("ReviewProductReactions");

                    b.Navigation("ReviewProductReplies");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.Role", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.Shape", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BE_Glowpurea.Models.StatusOrder", b =>
                {
                    b.Navigation("OrderStatusHistories");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
